# Generated by Django 3.1.3 on 2020-11-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code',
            field=models.TextField(default='', unique=True),
        ),
    ]
