# Generated by Django 3.1.3 on 2020-11-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_patient_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='updated',
            new_name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='owner',
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
    ]
