# Generated by Django 3.1.4 on 2020-12-09 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201125_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.TextField(default=uuid.uuid4, unique=True),
        ),
    ]
